alpha: 0.01
class_weights: !!python/object/apply:torch._utils._rebuild_tensor_v2
- !!python/object/apply:torch.storage._load_from_bytes
  - !!binary |
    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
    Z2UKcQFYDgAAADk1MDc5MDI0NjI4MDY0cQJYAwAAAGNwdXEDSwlOdHEEUS6AAl1xAFgOAAAAOTUw
    NzkwMjQ2MjgwNjRxAWEuCQAAAAAAAAAAAIA/DFlYQR5x50A20qE/AIAbQ3div0B0vok/4ysOQdy2
    sUE=
- 0
- !!python/tuple
  - 9
- !!python/tuple
  - 1
- false
- !!python/object/apply:collections.OrderedDict
  - []
l1_ratio: 0.5
lr: 0.0001
num_classes: 9
num_features: 149
